In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [8]:
img = cv2.imread('up.jpg',cv2.IMREAD_COLOR)
print(img.shape)
tmp = cv2.resize (img, (448, 448))
# cv2.imshow('title',tmp)

(1424, 1424, 3)


In [ ]:
plt.imshow(img)
plt.show()

In [ ]:
img = np.zeros((512,512,3), np.uint8)
img = cv2.line(img,(0,0),(511,511),(255,0,0),5)
plt.imshow(img)

In [ ]:
plt.imshow(cv2.rectangle(img,(384,0),(510,128),(0,5,5),3))


In [ ]:
img = cv2.circle(img, (447,63), 63, (0,0,255), -1)
plt.imshow(img)

In [ ]:
pts = np.array([[10,5], [20,30], [70,20], [50,10]], np.int32) # 각 꼭지점은 2차원 행렬로 선언
# 이미지에 표현하기 위해 3차원 행렬로 변환. 변환이전과 이후의 행렬 갯수는 동일해야함.
# -1은 원본에 해당하는 값을 그대로 유지.
pts = pts.reshape((-1, 1, 2))
img = cv2.polylines(img, [pts], True, (0,255,255))
plt.imshow(img)

In [ ]:
events = [i for i in dir(cv2) if 'EVENT' in i]

In [ ]:
print(events)

In [ ]:
def draw_circle(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        cv2.circle(img,(x,y), 100,(255,0,0),-1)

In [ ]:
img = np.zeros((512,512,3), np.uint8)
cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_circle)
while(1):
    cv2.imshow('image',img)
    if cv2.waitKey(0) & 0xFF == 27:
        break
cv2.destroyAllWindows()

In [ ]:
def nothing(x):
    pass

img = np.zeros((300,512,3), np.uint8)
cv2.namedWindow('image')

# trackbar를 생성하여 named window에 등록
cv2.createTrackbar('R', 'image', 0, 255, nothing)
cv2.createTrackbar('G', 'image', 0, 255, nothing)
cv2.createTrackbar('B', 'image', 0, 255, nothing)

switch = '0:OFF\n1:On'
cv2.createTrackbar(switch, 'image', 1, 1, nothing)

while(1):
    cv2.imshow('image', img)

    if cv2.waitKey(1) & 0xFF == 27:
        break

    r = cv2.getTrackbarPos('R','image')
    g = cv2.getTrackbarPos('G', 'image')
    b = cv2.getTrackbarPos('B', 'image')
    s = cv2.getTrackbarPos(switch, 'image')

    if s == 0:
        img[:] = 0 # 모든 행/열 좌표 값을 0으로 변경. 검은색
    else:
        img[:] = [b,g,r] # 모든 행/열 좌표값을 [b,g,r]로 변경

cv2.destroyAllWindows()

In [ ]:
img = cv2.imread('up.jpg',cv2.IMREAD_COLOR)
px = img[:]
print(px.shape)

In [ ]:
px.size

In [ ]:
b,g,r = cv2.split(px)
hsv = (cv2.cvtColor(px,cv2.COLOR_BGR2HSV))
lower_blue = np.array([110,50,50])
upper_blue = np.array([130,255,255])
mask = cv2.inRange(hsv,lower_blue,upper_blue)
res = cv2.bitwise_and(img,img,mask=mask)

plt.subplot(221)
plt.imshow(mask)
plt.subplot(222)
plt.imshow(res)
plt.subplot(223)
plt.imshow(img)

In [ ]:
import cv2
import numpy as np 
from matplotlib import pyplot as plt 

img = cv2.imread('up.jpg',0)
# img = cv2.medianBlur(img,5)

ret, th1 = cv2.threshold(img,127,255,cv2.THRESH_BINARY + cv2.THRESH_OTSU)



th2 = cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C,\
cv2.THRESH_BINARY,5,2)
th3 = cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\
cv2.THRESH_BINARY,5,2)

titles = ['Original','Global','Mean','Gaussian']

images = [img,th1,th2,th3]

for i in range(4):
	plt.subplot(2,2,i+1),plt.imshow(images[i],'gray')
	plt.title(titles[i])
	plt.xticks([]),plt.yticks([])

plt.show()

In [ ]:
img = cv2.imread('up.jpg',1)

# 행 : Height, 열:width
height, width = img.shape[:2]

# 이미지 축소
shrink = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)

# Manual Size지정
zoom1 = cv2.resize(img, (width*2, height*2), interpolation=cv2.INTER_CUBIC)

# 배수 Size지정
zoom2 = cv2.resize(img, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)


cv2.imshow('Origianl', img)
cv2.imshow('Shrink', shrink)
cv2.imshow('Zoom1', zoom1)
cv2.imshow('Zoom2', zoom2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
rows,cols = img.shape[:2]
print(rows,cols)
M = np.float32([[1,0,10],[0,1,20]])
dst = cv2.warpAffine(img,M,(cols,rows))
cv2.imshow('image',dst)

In [ ]:
from matplotlib import pyplot as plt

img = cv2.imread('up.jpg',0)
canny = cv2.Canny(img,30,70)

laplacian = cv2.Laplacian(img,cv2.CV_8U)
sobelx = cv2.Sobel(img,cv2.CV_8U,1,0,ksize=3)
sobely = cv2.Sobel(img,cv2.CV_8U,0,1,ksize=3)

images = [img,laplacian, sobelx, sobely, canny]
titles = ['Origianl', 'Laplacian', 'Sobel X', 'Sobel Y','Canny']

for i in range(5):
    plt.subplot(2,3,i+1),plt.imshow(images[i]),plt.title([titles[i]])
    plt.xticks([]),plt.yticks([])

plt.show()

In [9]:
img = cv2.imread('up.jpg',0)
lower_reso = cv2.pyrDown(img)
upper_reso = cv2.pyrUp(img)
cv2.imshow('img',upper_reso)
cv2.imshow('img',lower_reso)
cv2.imshow('img',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [17]:
kx,ky = cv2.getDerivKernels(1,0,ksize=3)
print(kx)
print(ky)

[[-1.]
 [ 0.]
 [ 1.]]
[[1.]
 [2.]
 [1.]]


In [14]:
sobelX = ky.dot(kx.T)
sobelX

array([[-1.,  0.,  1.],
       [-2.,  0.,  2.],
       [-1.,  0.,  1.]], dtype=float32)

In [20]:
blur = cv2.GaussianBlur(img,ksize=(7,7),sigmaX = 0.0)
cv2.imshow('blur',blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
edges1 = cv2.Canny(img,50,100)
cv2.imshow('edges1',edges1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
img = cv2.imread('up.jpg',0)
src = np.zeros(shape=(512,512,3),dtype=np.uint8)
ret,bimage = cv2.threshold(img,0,255,cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
print(ret)
cv2.imshow('bimage',bimage)
cv2.waitKey(0)
cv2.destroyAllWindows()

104.0


In [35]:
dist = cv2.distanceTransform(bimage,cv2.DIST_L1,3)
minVal,maxVal,minLoc,maxLoc = cv2.minMaxLoc(dist)
mask = (dist>maxVal *0.5).astype(np.uint8)*255
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
data = img.reshape((-1,2)).astype(np.float32)
print(data)

[[111. 111.]
 [109. 106.]
 [101.  96.]
 ...
 [122. 122.]
 [113. 121.]
 [120. 122.]]


In [40]:
K=2
term_crit = (cv2.TERM_CRITERIA_EPS)


In [42]:
res = cv2.cornerEigenValsAndVecs(img,blockSize=5,ksize=3)
res.shape

(1424, 1424, 6)

In [44]:
eigen =cv2.split(res)
eigen

[array([[0.00027648, 0.00027134, 0.00033722, ..., 0.00088565, 0.0008015 ,
         0.00073064],
        [0.00055037, 0.00051481, 0.00049081, ..., 0.00096614, 0.00097479,
         0.000963  ],
        [0.00063646, 0.00058146, 0.00052499, ..., 0.00126505, 0.00120039,
         0.00120352],
        ...,
        [0.00048734, 0.00042669, 0.00033012, ..., 0.00015646, 0.00018066,
         0.00020398],
        [0.000264  , 0.00022034, 0.00017432, ..., 0.00019119, 0.0002196 ,
         0.00025462],
        [0.00037878, 0.0002897 , 0.00022769, ..., 0.0002094 , 0.00025334,
         0.00028159]], dtype=float32),
 array([[1.75962545e-04, 1.81099327e-04, 1.63664590e-04, ...,
         7.52114502e-05, 2.63398451e-05, 2.99942531e-05],
        [1.62589524e-04, 1.91765168e-04, 2.72815494e-04, ...,
         8.62218658e-05, 2.42917613e-05, 2.89314066e-05],
        [1.74767221e-04, 2.15307329e-04, 2.68012634e-04, ...,
         1.33408714e-04, 1.00569574e-04, 1.01820624e-04],
        ...,
        [2.13777021e-

In [2]:
def distance(f1,f2):
    x1,y1 = f1.pt
    x2,y2 = f2.pt
    return np.sqrt((x2-x1)**2 + (y2-y1)**2)

In [3]:
def filteringByDistance(kp,distE = 0.5):
    size = len(kp)
    mask = np.arrange(1,size+1).astype(np.bool8)
    for i , f1 in enumerate(kp):
        if not mask[i]:
            continue
        else:
            for j , f2 in enumerate(kp):
                if i==j:
                    continue
                if distance(f1,f2)< distE:
                    mask[j]=False
    np_kp = np.array(kp)
    return list(np_kp[mask])

In [5]:
img = cv2.imread('up.jpg',0)
gray = cv2.GaussianBlur(img,(5,5),0.0)

In [6]:
briskF = cv2.BRISK_create()
kp = briskF.detect(gray)
dst = cv2.drawKeypoints(gray,kp,None,color=(0,0,255))
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [16]:
img = cv2.imread('up.jpg',0)
ret,bimage = cv2.threshold(img,220,255,cv2.THRESH_BINARY_INV)
bimage = cv2.dilate(bimage,None)
# cv2.imshow('bimage',bimage)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

mode = cv2.RETR_EXTERNAL
method = cv2.CHAIN_APPROX_SIMPLE
image,contours,hierarchy = cv2.findContours(bimage,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
maxLength = 0
k=0
for i,cnt in enumerate(contours):
    perimeter = cv2.arcLength(cnt,closed=True)
    if perimeter > maxLength:
        maxLength = perimeter
        k=i
print('maxLength',maxLength)
cnt=contours[k]
dst2=img.copy()
cv2.drawContours(dst2,[cnt],0,(255,0,0),3)
cv2.waitKey(0)
cv2.destroyAllWindows()

ValueError: not enough values to unpack (expected 3, got 2)

In [12]:
dst2=img.copy()
cnt = contours[0]
rows,cols = dst2.shape[:2]
[vx,vy,x,y] = cv2.fitLine(cnt,cv2.DIST_L2,0,0.01,0.01)
y1=int((-x * vy/vx) +y)
y2 = int(((cols-x)*vy/vx)+y)
cv2.line(dst2,(0,y1),(cols-1,y2),(0,0,255),2)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'cnt' is not defined

In [19]:
A=np.arange(1,17).reshape(4,4).astype(np.uint8)
print(A)
sumA,sqsumA,tiltedA = cv2.integral3(A)
print(sumA)
print(sqsumA)
print(tiltedA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[  0   0   0   0   0]
 [  0   1   3   6  10]
 [  0   6  14  24  36]
 [  0  15  33  54  78]
 [  0  28  60  96 136]]
[[0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 1.000e+00 5.000e+00 1.400e+01 3.000e+01]
 [0.000e+00 2.600e+01 6.600e+01 1.240e+02 2.040e+02]
 [0.000e+00 1.070e+02 2.470e+02 4.260e+02 6.500e+02]
 [0.000e+00 2.760e+02 6.120e+02 1.016e+03 1.496e+03]]
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 1  8 12 16 15]
 [ 8 26 38 42 36]
 [26 60 80 84 70]]


In [20]:
gray_sum = cv2.integral(img)
dst = cv2.normalize(gray_sum,None,0,255,
                   cv2.NORM_MINMAX,dtype = cv2.CV_8U)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
def rectSum(sumImage,rect):
    x,y,w,h = rect
    a = sumImage[y,x]
    b = sumImage[y,x+w]
    c = sumImage[y+h,x]
    d = sumImage[y+h,x+w]
    return a+d-b-c
def compute_Haar_feature1(sumImage,rect):
    x,y,w,h=rect
    s1=rectSum(sumImage,(x,y,w,h))
    s2=rectSum(sumImage,(x+w,y,w,h))
    return s1 -s2

def compute_Haar_feature2(sumImage,rect):
    x,y,w,h=rect
    s1=rectSum(sumImage,(x,y,w,h))
    s2=rectSum(sumImage,(x,y+h,w,h))
    return s2 -s1


In [23]:
A = np.arange(1,6*6 +1).reshape(6,6).astype(np.uint8)
print(A)
h,w=A.shape
sumA = cv2.integral(A)
print(sumA)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[  0   0   0   0   0   0   0]
 [  0   1   3   6  10  15  21]
 [  0   8  18  30  44  60  78]
 [  0  21  45  72 102 135 171]
 [  0  40  84 132 184 240 300]
 [  0  65 135 210 290 375 465]
 [  0  96 198 306 420 540 666]]


In [24]:
compute_Haar_feature1(sumA,(0,0,w//2,h))

-54

In [25]:
compute_Haar_feature2(sumA,(0,0,w,h//2))

324